### ISSUE TITLE
nacos1.2.1版本web界面手动创建服务后，会被系统自动删除，这个现象是否正常？

### ISSUE THREAD

**Issue by qwerplf** [nacos-group/nacos-k8s#127]
外部的pv + 外部mysql+ 修改后的nacos-quick-start.yaml  部署结束后，nacos集群选出了leader,集群无报错,如下图：
![image](https://user-images.githubusercontent.com/23162792/82651360-a4884e80-9c4e-11ea-909d-0235a87e959c.png)
web界面中也有显示：
![image](https://user-images.githubusercontent.com/23162792/82651493-d00b3900-9c4e-11ea-9a9a-9c40217e79b2.png)
但是问题是，我手动在web界面创建服务，大约1分钟后，服务就被自动删除了。我能够在naming-raft.log日志中看到创建，删除的痕迹。这个是正常的吗？
![image](https://user-images.githubusercontent.com/23162792/82652124-aef71800-9c4f-11ea-872c-7e2aead483f3.png)
![image](https://user-images.githubusercontent.com/23162792/82652186-c33b1500-9c4f-11ea-9dbb-6e80840ee2af.png)
![image](https://user-images.githubusercontent.com/23162792/82652439-33e23180-9c50-11ea-8839-9d2be98b222a.png)

**Comment by qwerplf** [comment]
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos-headless
  namespace: nacos
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: nacos
data:
  mysql.address: "192.168.253.48"
  mysql.db.name: "nacos"
  mysql.port: "3306"
  mysql.user: "root"
  mysql.password: "nacos@plf2020"
  JVM_XMS: "800m"
  JVM_XMX: "1g"
  JVM_XMN: "256m"
  JVM_MS: "256m"
  JVM_MMS: "256m"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: nacos
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos-headless
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: nacos-service-account
      containers:
        - name: k8snacos
          imagePullPolicy: Always
          image: nacos/nacos-server:latest
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 8848
              name: client
          env:
            - name: JVM_XMX
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: JVM_XMX
            - name: JVM_XMS
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: JVM_XMS
            - name: JVM_XMN
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: JVM_XMN
            - name: JVM_MS
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: JVM_MS
            - name: JVM_MMS
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: JVM_MMS
            - name: NACOS_REPLICAS
              value: "3"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.address
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.nacos.svc.cluster.local:8848 nacos-1.nacos-headless.nacos.svc.cluster.local:8848 nacos-2.nacos-headless.nacos.svc.cluster.local:8848"
          volumeMounts:
            - name: datadir
              mountPath: /home/nacos/data
            - name: logdir
              mountPath: /home/nacos/logs
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "cbs"
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: logdir
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "cbs"
        resources:
          requests:
            storage: 10Gi
  selector:
    matchLabels:
      app: nacos

**Comment by qwerplf** [comment]
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos-headless
  namespace: nacos
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: nacos
data:
  mysql.address: "192.168.253.48"
  mysql.db.name: "nacos"
  mysql.port: "3306"
  mysql.user: "root"
  mysql.password: "nacos@plf2020"
  JVM_XMS: "800m"
  JVM_XMX: "1g"
  JVM_XMN: "256m"
  JVM_MS: "256m"
  JVM_MMS: "256m"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: nacos
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos-headless
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: nacos-service-account
      containers:
        - name: k8snacos
          imagePullPolicy: Always
          image: nacos/nacos-server:latest
          resources:
            requests:
              memory: "500Mi"
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 8848
              name: client
          env:
            - name: JVM_XMX
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: JVM_XMX
            - name: JVM_XMS
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: JVM_XMS
            - name: JVM_XMN
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: JVM_XMN
            - name: JVM_MS
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: JVM_MS
            - name: JVM_MMS
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: JVM_MMS
            - name: NACOS_REPLICAS
              value: "3"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.address
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.nacos.svc.cluster.local:8848 nacos-1.nacos-headless.nacos.svc.cluster.local:8848 nacos-2.nacos-headless.nacos.svc.cluster.local:8848"
          volumeMounts:
            - name: datadir
              mountPath: /home/nacos/data
            - name: logdir
              mountPath: /home/nacos/logs
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "cbs"
        resources:
          requests:
            storage: 10Gi
    - metadata:
        name: logdir
      spec:
        accessModes: [ "ReadWriteMany" ]
        storageClassName: "cbs"
        resources:
          requests:
            storage: 10Gi
  selector:
    matchLabels:
      app: nacos
```
