### ISSUE TITLE
helm 安装中出现的一些问题 主要关于StorageClass

### ISSUE THREAD

**Issue by bbqtk** [nacos-group/nacos-k8s#130]
非常感谢您对Naocs-helm的付出，但是我们在使用helm安装Nacos的过程中出现了一些有趣的问题

- StorageClass未提供安装开关
 当前的helm安装文件中 ，在对StorageClass的定义中虽然提供了
{{- if and .Values.mysql.persistence.enabled (not .Values.mysql.persistence.existingClaim) -}}作为总开关；但是在
```
{{- if not .Values.mysql.persistence.enabled }}
      volumes:
      - name: mysql-data
        emptyDir: {}
      {{- else if .Values.mysql.persistence.existingClaim }}
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: {{ .Values.mysql.persistence.existingClaim }}
      {{- end }}
```
并未提供单独选择使用PVC而不创建StorageClass的开关，因为他们公用一个总开关
.Values.mysql.persistence.enabled

这样对于使用云厂商Kubernetes集群的用户来说 ，有很多不便，因为这些用户大部分会去使用厂商提供的StorageClass，而并非通过NFS去创建StorageClass。

期待您的交流
