### ISSUE TITLE
支持 nacos 1.3.0 embedded 启动模式嘛

### ISSUE THREAD

**Issue by ifnn** [nacos-group/nacos-k8s#135]

**Comment by jenphyjohn** [comment]
同问

**Comment by paderlol** [comment]
可以的，不过推荐使用挂卷的方式去做，移除掉数据库配置，并且环境变量指定使用Embedded就可以了

**Comment by ifnn** [comment]
> 可以的，不过推荐使用挂卷的方式去做，移除掉数据库配置，并且环境变量指定使用Embedded就可以了

能否出一个大概的 yaml 配置信息,这个环境变量指定的具体内容能否告知一下

**Comment by wangweizZZ** [comment]
> > 可以的，不过推荐使用挂卷的方式去做，移除掉数据库配置，并且环境变量指定使用Embedded就可以了
> 
> 能否出一个大概的 yaml 配置信息,这个环境变量指定的具体内容能否告知一下

主要是 EMBEDDED_STORAGE 这个环节变量吧，例如试试如下
```
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos-headless
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
      nodePort: 31848
  selector:
    app: nacos
  type: NodePort
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos-headless
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: k8snacos
          imagePullPolicy: Always
          image: nacos/nacos-server:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: EMBEDDED_STORAGE
              value: "embedded"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.default.svc.cluster.local:8848 nacos-1.nacos-headless.default.svc.cluster.local:8848 nacos-2.nacos-headless.default.svc.cluster.local:8848"
  selector:
    matchLabels:
      app: nacos
```
