### ISSUE TITLE
采用现有数据库部署, 启动报错: java.sql.SQLSyntaxErrorException: Table 'nacos-int.config_info' doesn't exist

### ISSUE THREAD

**Issue by xiaozhongliu** [nacos-group/nacos-k8s#138]
问题如题所述, 截图如下:
![image](https://user-images.githubusercontent.com/17674404/87533411-259c1900-c6c7-11ea-83ee-36d4ab309029.png)

数据库: 使用现有mysql
volume: 使用阿里云盘
部署yml完整内容如下:
```yml
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  namespace: infras
  labels:
    app: nacos
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  clusterIP: None
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
  namespace: infras
data:
  mysql.db.hostname: ******.mysql.rds.aliyuncs.com
  mysql.db.name: ******
  mysql.port: '3306'
  mysql.user: ******
  mysql.password: ******
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
  namespace: infras
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: 'true'
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: 'app'
                    operator: In
                    values:
                      - nacos
              topologyKey: 'kubernetes.io/hostname'
      initContainers:
        - name: peer-finder-plugin-install
          image: nacos/nacos-peer-finder-plugin:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: volume
              mountPath: /home/nacos/plugins/peer-finder
              subPath: plguindir
      containers:
        - name: nacos
          imagePullPolicy: Always
          image: nacos/nacos-server:1.3.1
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - containerPort: 8848
              name: client-port
          env:
            - name: NACOS_REPLICAS
              value: '2'
            - name: SERVICE_NAME
              value: 'nacos-headless'
            - name: DOMAIN_NAME
              value: 'cluster.local'
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.hostname
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: NACOS_SERVER_PORT
              value: '8848'
            - name: NACOS_APPLICATION_PORT
              value: '8848'
            - name: PREFER_HOST_MODE
              value: 'hostname'
          volumeMounts:
            - name: volume
              mountPath: /home/nacos/plugins/peer-finder
              subPath: plguindir
            - name: volume
              mountPath: /home/nacos/data
              subPath: datadir
            - name: volume
              mountPath: /home/nacos/logs
              subPath: logdir
  volumeClaimTemplates:
    - metadata:
        name: volume
      spec:
        accessModes: ['ReadWriteMany']
        storageClassName: alicloud-disk-efficiency
        resources:
          requests:
            storage: 20Gi
  selector:
    matchLabels:
      app: nacos
```
