### ISSUE TITLE
java.lang.IllegalStateException: can not find peer: nacos-0.nacos-hs.default.svc.cluster.local:8848

### ISSUE THREAD

**Issue by bbqtk** [nacos-group/nacos-k8s#142]
## 我不知道是否遇到了相似的问题，但是我觉得应该在该issue中提供说明。
- 我同样在k8s中进行nacos cluster模式部署，部署3台
- 当前使用的k8s版本为1.16.3版本，Nacos版本为1.3.1最新版本。
- 使用过程中，我发现在使用过程中，界面中会出现一些报错如下：
<img width="759" alt="截屏2020-07-29 上午11 32 59" src="https://user-images.githubusercontent.com/19991733/88753665-56805180-d18f-11ea-911f-b80f04c54b02.png">
- 我进入到后台日志目录下，查看 nacos.log 出现以下错误
<img width="1400" alt="截屏2020-07-29 上午11 46 44" src="https://user-images.githubusercontent.com/19991733/88754418-30f44780-d191-11ea-9b05-d3f41fc86a4c.png">

**Comment by paderlol** [comment]
你这是选主都没成功,你修改了Service的名称,环境变量那里改了吗？这个变量SERVICE_NAME

**Comment by bbqtk** [comment]
我并未改变这里的值，一直使用的是 nacos-hs，并且，我看start.out日志中显示，集群模式启动成功。
<img width="398" alt="截屏2020-07-29 下午12 54 13" src="https://user-images.githubusercontent.com/19991733/88758268-9dc00f80-d19a-11ea-9cf2-07fe4aeceba1.png">

**Comment by bbqtk** [comment]
<img width="861" alt="截屏2020-07-29 下午12 55 19" src="https://user-images.githubusercontent.com/19991733/88758328-c516dc80-d19a-11ea-9ddb-94d34d80274d.png">

**Comment by bbqtk** [comment]
<img width="2535" alt="截屏2020-07-29 下午12 58 04" src="https://user-images.githubusercontent.com/19991733/88758497-2939a080-d19b-11ea-8b5a-437d7216fc44.png">
我通过查询API，显示是选主成功的

**Comment by paderlol** [comment]
你能看到控制台的集群列表吗？

**Comment by bbqtk** [comment]
<img width="2367" alt="截屏2020-07-29 下午1 01 06" src="https://user-images.githubusercontent.com/19991733/88758721-ad8c2380-d19b-11ea-8171-5e63d7b0c5b5.png">

**Comment by paderlol** [comment]
这个是在做什么操作的时候会出现呢？

**Comment by paderlol** [comment]
看这个图.你第一个节点都没有加入集群.都没完全没有参与投票

**Comment by paderlol** [comment]
你可以去看下容器里面cluster.conf 配置集群文件节点是否配置了三个,第二个看下nacos-0节点之间是否可以通讯

**Comment by bbqtk** [comment]
在查看服务列表中会出现这种情况，操作方式如下
- 刷新服务列表 ！！请注意看avatar-server这个服务
<img width="859" alt="截屏2020-07-29 下午1 08 05" src="https://user-images.githubusercontent.com/19991733/88759073-8e41c600-d19c-11ea-8495-6fdfb8fd9ac8.png">
- 再刷新服务列表 ！！ 请注意看 avatar-server 这个服务就消失了
<img width="887" alt="截屏2020-07-29 下午1 13 31" src="https://user-images.githubusercontent.com/19991733/88759408-4e2f1300-d19d-11ea-8e6f-4b081fe57bd9.png">

**Comment by bbqtk** [comment]
然后这个时候，如果我点击avatar-server的详情按钮，就会出现
<img width="759" alt="截屏2020-07-29 下午1 15 17" src="https://user-images.githubusercontent.com/19991733/88759521-8df5fa80-d19d-11ea-97ee-71168dff7237.png">

**Comment by bbqtk** [comment]
有时候第一次点进去会显示正常，有时候就是这个错误出现了

**Comment by bbqtk** [comment]
<img width="1006" alt="截屏2020-07-29 下午1 19 36" src="https://user-images.githubusercontent.com/19991733/88759819-28563e00-d19e-11ea-8081-a4e3146e0530.png">

**Comment by bbqtk** [comment]
<img width="995" alt="截屏2020-07-29 下午1 28 56" src="https://user-images.githubusercontent.com/19991733/88760360-761f7600-d19f-11ea-999a-3b4c5bd28561.png">
节点之间的t通讯，也应该是无问题的

**Comment by paderlol** [comment]
应该是Nacos0的只有一部分数据，nacos1和nacos2自己形成了集群，而nacos0没有进来

**Comment by bbqtk** [comment]
<img width="399" alt="截屏2020-07-29 下午1 39 27" src="https://user-images.githubusercontent.com/19991733/88761078-f7c3d380-d1a0-11ea-9ce9-a996c9487d7d.png">
是否与我设置了健康检查有关？

**Comment by paderlol** [comment]
有，这个后面的接口去掉了，所以不要拿这个做验证，会造成节点重启，你看下你的pod列表上面是否有重新启动次数

**Comment by bbqtk** [comment]
<img width="2424" alt="截屏2020-07-29 下午1 43 27" src="https://user-images.githubusercontent.com/19991733/88761317-7caeed00-d1a1-11ea-9aa6-187dc6854e57.png">
没有c重启过哎，我是通过将那个配置打开了，来检测的

**Comment by bbqtk** [comment]
management.endpoints.web.exposure.include=* 指标收集参数我设置开启了

**Comment by bbqtk** [comment]
<img width="676" alt="截屏2020-07-29 下午1 45 55" src="https://user-images.githubusercontent.com/19991733/88761497-d7e0df80-d1a1-11ea-9052-d1a3b20d4624.png">
 我检测过，相关接口，在1.3.1也是有的

**Comment by paderlol** [comment]
哦哦 你这个不是Nacos提供的 所以设置也没什么问题,但是你这个Nacos0是没有进入集群的

**Comment by bbqtk** [comment]
我是否可以通过重启nacos-0这个节点来解决改问题？

**Comment by paderlol** [comment]
可以尝试下 但是我尝试重现你的情况 无法重现出来

**Comment by bbqtk** [comment]
<img width="865" alt="截屏2020-07-29 下午1 53 04" src="https://user-images.githubusercontent.com/19991733/88761997-db289b00-d1a2-11ea-96fb-7975982a1fe7.png">
我看到的情况比较奇怪，跟刚才看到集群情况又变了，节点元数据

**Comment by paderlol** [comment]
你已经重启了吗？

**Comment by paderlol** [comment]
再用api看下当前的leader情况看看

**Comment by bbqtk** [comment]
<img width="2530" alt="截屏2020-07-29 下午1 57 49" src="https://user-images.githubusercontent.com/19991733/88762438-c6003c00-d1a3-11ea-9922-282f90d07ede.png">
<img width="2528" alt="截屏2020-07-29 下午1 58 00" src="https://user-images.githubusercontent.com/19991733/88762451-cdbfe080-d1a3-11ea-929c-948b642f757b.png">
<img width="2534" alt="截屏2020-07-29 下午1 58 16" src="https://user-images.githubusercontent.com/19991733/88762464-d44e5800-d1a3-11ea-9874-0a628192b6ce.png">

**Comment by bbqtk** [comment]
我目前并没有使用 NFS StorageClass ，是否会影响集群环境下的Nacos？ 以下是我目前的value文件
```
affinity: {}
annotations: {}
apm:
  config:
    sw_agent_collector_backend_services: skywalking-oap.default.svc.cluster.local:11800
    sw_agent_name: nacos
env:
  domainName: cluster.local
  preferhostmode: hostname
  serverPort: 8848
global:
  mode: cluster
  storageClass:
    provisioner: null
health:
  enabled: false
image:
  pullPolicy: IfNotPresent
  repository: *******/****-backend/nacos-server
  tag: 1.3.0.alpha
imagePullSecrets:
- name: open-vmuse-fun
ingress:
  annotations:
    kubernetes.io/ingress.class: traefik
  enabled: true
  hosts:
  - host: ***-sky.mmmm.fun
    paths:
    - /nacos
  tls: []
initContainers:
  initimageversion: 8.0.1
  initrepositoryimage: ***.****/***-backend/skywalking-agent
  pullPolicy: IfNotPresent
mysql:
  affinity: {}
  annotations: {}
  classParameters: {}
  database: nacos_devtest
  global:
    mode: cluster
    storageClass:
      provisioner: null
  image:
    pullPolicy: IfNotPresent
    repository: nacos/nacos-mysql
    tag: 5.7
  mysql:
    affinity: {}
    annotations: {}
    classParameters: {}
    database: nacos_devtest
    image:
      pullPolicy: IfNotPresent
      repository: nacos/nacos-mysql
      tag: 5.7
    nodeSelector: {}
    password: nacos
    persistence:
      claim:
        name: mysql-data
        spec:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 5G
          storageClassName: sc-mysql
      enabled: false
      existingClaim: mysql-data
    resources: {}
    rootPassword: root
    service:
      port: 3306
    tolerations: {}
    user: nacos
  nodeSelector: {}
  password: nacos
  persistence:
    claim:
      name: mysql-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 5G
        storageClassName: sc-mysql
    enabled: false
    existingClaim: mysql-data
  resources: {}
  rootPassword: root
  service:
    port: 3306
  tolerations: {}
  user: nacos
nodeSelector: {}
persistence:
  classParameters: {}
  data:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: manual
  enabled: false
  log:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: manual
  plugin:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: manual
  storageClassName: sc-nacos
replicaCount: 3
resources:
  requests:
    cpu: 500m
    memory: 2Gi
service:
  name: nacos
  port: 8848
  type: ClusterIP
serviceMonitor:
  create: true
tolerations: []

```
