### ISSUE TITLE
Caused by: com.alibaba.nacos.api.exception.NacosException: java.net.UnknownHostException: jmenv.tbsite.net

### ISSUE THREAD

**Issue by ronwxy** [nacos-group/nacos-k8s#153]
k8s version: 1.16
使用nacos-pvc-nfs.yaml，`kubectl create -f nacos-k8s/deploy/nacos/nacos-pvc-nfs.yaml` 启动时报异常

`nested exception is ErrCode:500, ErrMsg:jmenv.tbsite.net
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:184)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300)
	... 112 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: java.net.UnknownHostException: jmenv.tbsite.net
	at com.alibaba.nacos.core.cluster.lookup.AddressServerMemberLookup.run(AddressServerMemberLookup.java:118)
	at com.alibaba.nacos.core.cluster.lookup.AddressServerMemberLookup.start(AddressServerMemberLookup.java:75)
	at com.alibaba.nacos.core.cluster.ServerMemberManager.initAndStartLookup(ServerMemberManager.java:154)
	at com.alibaba.nacos.core.cluster.ServerMemberManager.init(ServerMemberManager.java:143)
	at com.alibaba.nacos.core.cluster.ServerMemberManager.<init>(ServerMemberManager.java:128)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:172)
	... 114 common frames omitted
Caused by: java.net.UnknownHostException: jmenv.tbsite.net
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.alibaba.nacos.common.http.BaseHttpClient.execute(BaseHttpClient.java:47)
	at com.alibaba.nacos.common.http.NacosSyncHttpClient.get(NacosSyncHttpClient.java:46)
	at com.alibaba.nacos.core.cluster.lookup.AddressServerMemberLookup.syncFromAddressUrl(AddressServerMemberLookup.java:141)
	at com.alibaba.nacos.core.cluster.lookup.AddressServerMemberLookup.run(AddressServerMemberLookup.java:109)
	... 123 common frames omitted
`

有遇到过的吗， 如何处理？

**Comment by ronwxy** [comment]
@HiroC222  @paderlol 大佬帮看看。

**Comment by paderlol** [comment]
参考 这个https://github.com/nacos-group/nacos-k8s/issues/144

**Comment by paderlol** [comment]
然后确保自己的NFS都是正常能访问,以及ClusterType设置为NONE

**Comment by ronwxy** [comment]
参考了的。 NFS能正常访问
![image](https://user-images.githubusercontent.com/3346696/92067976-4257f180-edd8-11ea-9aaf-7064e92bf123.png)


配置文件 nacos-k8s/deploy/nacos/nacos-pvc-nfs.yaml 内容：

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  clusterIP: None
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  mysql.db.name: "nacos_devtest"
  mysql.port: "3306"
  mysql.user: "nacos"
  mysql.password: "nacos"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "kubernetes.io/hostname"
      serviceAccountName: nfs-client-provisioner
      containers:
        - name: nacos
          imagePullPolicy: Always
          image: nacos/nacos-server:latest
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
          ports:
            - containerPort: 8848
              name: client-port
          env:
            - name: NACOS_REPLICAS
              value: "3"
            - name: SERVICE_NAME
              value: "nacos-headless"
            - name: DOMAIN_NAME
              value: "cluster.local"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: MODE
              value: "cluster"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: NACOS_APPLICATION_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.default.svc.cluster.local:8848 nacos-1.nacos-headless.default.svc.cluster.local:8848 nacos-2.nacos-headless.default.svc.cluster.local:8848"
          volumeMounts:
            - name: plugindir
              mountPath: /home/nacos/plugins/peer-finder
            - name: datadir
              mountPath: /home/nacos/data
            - name: logdir
              mountPath: /home/nacos/logs
  volumeClaimTemplates:
    - metadata:
        name: plugindir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: datadir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
    - metadata:
        name: logdir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
  selector:
    matchLabels:
      app: nacos
```

仍然报这个错。

**Comment by paderlol** [comment]
确定下自己的k8s domain没有带 svc.cluster.local.  然后进入容器看下cluster.conf有没有写入

**Comment by paderlol** [comment]
确定这个参数--cluster_domain是不是cluster.local. 如果带了点就不行，这需要修改成不带点的或者，你配置
- name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.default.svc.cluster.local.:8848 nacos-1.nacos-headless.default.svc.cluster.local.:8848 nacos-2.nacos-headless.default.svc.cluster.local.:8848"

给所有的域名最后加上.  上面的配置我加过.了

**Comment by ronwxy** [comment]
> 确定这个参数--cluster_domain是不是cluster.local. 如果带了点就不行，这需要修改成不带点的或者，你配置
> 
> * name: NACOS_SERVERS
>   value: "nacos-0.nacos-headless.default.svc.cluster.local.:8848 nacos-1.nacos-headless.default.svc.cluster.local.:8848 nacos-2.nacos-headless.default.svc.cluster.local.:8848"
> 
> 给所有的域名最后加上. 上面的配置我加过.了

直接 docker run 能跑起来

```shell
docker run -it --rm -p 8848:8848 -e DOMAIN_NAME=cluster.local -e MYSQL_SERVICE_DB_NAME=nacos_devtest -e MYSQL_SERVICE_PORT=3306 -e MYSQL_SERVICE_USER=nacos -e MYSQL_SERVICE_PASSWORD=nacos -e MYSQL_SERVICE_HOST=10.111.0.251 -e MODE=cluster -e NACOS_SERVER_PORT=8848 -e NACOS_APPLICATION_PORT=8848 -e PREFER_HOST_MODE=hostname -e NACOS_SERVERS="nacos-0.nacos-headless.default.svc.cluster.local:8848" nacos/nacos-server
```
进容器后能看到 cluster.conf

```shell
cat conf/cluster.conf 
#2020-09-03T14:05:43.643
21c67ab482d1:8848
nacos-0.nacos-headless.default.svc.cluster.local:8848
```

cluster.local 这个应该没动过， 按默认的，yaml配置里也加了环境变量

 - name: DOMAIN_NAME
   value: "cluster.local"

但k8s里启动就报错了

**Comment by paderlol** [comment]
我说的是k8s自己的dns，不是nacos的变量

**Comment by paderlol** [comment]
你可以进入容器自己输入hostname -f

**Comment by paderlol** [comment]
这跟docker能不能跑根本没有任何关系

**Comment by paderlol** [comment]
如果你不能理解,麻烦按照下面操作 
进入容器hostname -f 确认是否域名后面多了一个点,这是K8s core dns --cluster_domain导致的.

解决办法 改掉NACOS_SERVERS的值
请看仔细,这里面每个域名后面都加了点 `.`
``` yaml
  - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.default.svc.cluster.local.:8848 nacos-1.nacos-headless.default.svc.cluster.local.:8848 nacos-2.nacos-headless.default.svc.cluster.local.:8848"
          
```

**Comment by ronwxy** [comment]
因为k8s pod 没启动成功， 所以没法进入。 进其他的pod，执行hostname -f 后面是没有点的。 

```shell
[root@kmaster k8s-deploy]# kubectl exec -it nfs-client-provisioner-88b9c6945-8fdkq sh 
/ # hostname -f
nfs-client-provisioner-88b9c6945-8fdkq
```

同时我把NACOS_SERVERS 按照你这边的写法， 也还是一样的报错： Caused by: java.net.UnknownHostException: jmenv.tbsite.net。。。

**Comment by ronwxy** [comment]
另外查看nacos pod日志， 
有 ` lookup nacos-headless on 10.96.0.10:53: read udp 10.244.2.45:48660->10.96.0.10:53: i/o timeout` 错误

```
+ nohup /usr/lib/jvm/java-1.8.0-openjdk/bin/java -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.preferHostnameOverIp=true -Dnacos.member.list= -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/health:/home/nacos/plugins/cmdb:/home/nacos/plugins/mysql -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/ --spring.config.name=application,custom --logging.config=/home/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
+ echo '/usr/lib/jvm/java-1.8.0-openjdk/bin/java  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.preferHostnameOverIp=true -Dnacos.member.list= -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/health:/home/nacos/plugins/cmdb:/home/nacos/plugins/mysql -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/ --spring.config.name=application,custom --logging.config=/home/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288'
**2020/09/03 15:11:46 lookup nacos-headless on 10.96.0.10:53: read udp 10.244.2.45:48660->10.96.0.10:53: i/o timeout**
```

**Comment by paderlol** [comment]
找到文件里面的以下两个配置移除掉
``` yaml
 - name: plugindir
mountPath: /home/nacos/plugins/peer-finder

    - metadata:
        name: plugindir
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 5Gi
```
