### ISSUE TITLE
关于k8s部署yaml配置问题

### ISSUE THREAD

**Issue by warthur1214** [nacos-group/nacos-k8s#213]
我想在两个k8s节点上部署3个以上的pod，提示我pod 亲和度podAntiAffinity问题：
那么我可以去掉下面这段配置么？
```
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos
              topologyKey: "kubernetes.io/hostname"
```
