### ISSUE TITLE
k8s ingress配置了9488端口，本地启动服务，注册nacos失败

### ISSUE THREAD

**Issue by zhangwei900808** [nacos-group/nacos-k8s#233]
![image](https://user-images.githubusercontent.com/4385154/124436670-ca1bdd00-dda8-11eb-8a14-b1eaee2b89eb.png)
![image](https://user-images.githubusercontent.com/4385154/124436713-d7d16280-dda8-11eb-9f02-75e9bd817db5.png)

**Comment by zhangwei900808** [comment]
![image](https://user-images.githubusercontent.com/4385154/124436791-ee77b980-dda8-11eb-9c86-90aeae5a278c.png)
这是k8s ingress的截图

**Comment by paderlol** [comment]
2.0 8848+1000的grpc端口也要放出来，自己看下Nacos官方文档，如果你用了反代那么以你反代的端口+1000才是grpc端口

**Comment by zhangwei900808** [comment]
```
rules:
    - host: server.seaurl.com
      http:
        paths:
          - path: /nacos
            backend:
              serviceName: nacos-headless
              servicePort: server
          - path: /a
            backend:
              serviceName: nacos-headless
              servicePort: client-rpc
```
@paderlol 我这样写不就是放开了9488端口了吗

**Comment by zhangwei900808** [comment]
@paderlol 你的意思是说80+1000=1080?

**Comment by zhangwei900808** [comment]
@paderlol 意思我明白了，可是怎么写啊，我有点无从下手，哈哈

**Comment by paderlol** [comment]
只能代理8848最好，因为内部会用同一个域名连加1000端口

**Comment by zhangwei900808** [comment]
@paderlol 有个问题就是我使用的是你们提供的nacos-no-pvc-ingress.yaml文件，为什么你们这个文件里面不写好呢？而且也没注释说明，难道这个只能自己手动解决吗

**Comment by zhangwei900808** [comment]
解决了，我把ingress的path: /nacos替换成/就可以用域名来访问了，困扰我好长时间的问题终于解决了。
```
  rules:
    - host: nacos.alibaba.com
      http:
        paths:
          - path: /
            backend:
              serviceName: nacos-headless
              servicePort: server
```
