### ISSUE TITLE
operator下如何设置DOMAIN_NAME

### ISSUE THREAD

**Issue by yylstudy** [nacos-group/nacos-k8s#325]
operator方式部署nacos集群如何设置DOMAIN_NAME

**Comment by shenkonghui** [comment]
@yylstudy 
DOMAIN_NAME应该是通过环境变量配置，可以试试这样
```
apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  name: nacos
spec:
  env:
  - name: DOMAIN_NAME
    value: "cluster.local"
...
```
