### ISSUE TITLE
operator: can't get prometheus metrics on nacos-server v2.1.1

### ISSUE THREAD

**Issue by rnyrnyrny** [nacos-group/nacos-k8s#344]
使用operator部署nacos集群，镜像版本v2.1.1，按照Nacos 监控手册的指南，在config里配置了`management.endpoints.web.exposure.include=*`，然而访问`/nacos/actuator/prometheus`得到的是一个404的Whitelabel Error Page.
看了下nacos-server的启动脚本，v2.1.1版本镜像已经不会读取init.d里面的配置了：
https://github.com/nacos-group/nacos-docker/commit/4f16131a4cc6709e6316495a20d656c74514ee9d
尝试在env里面加上两个环境变量：
```yaml
  env:
  - name: CUSTOM_SEARCH_NAMES
    value: "application,custom"
  - name: CUSTOM_SEARCH_LOCATIONS
    value: "/home/nacos/init.d/,file:/home/nacos/conf/"
```
结果还是一样
