### ISSUE TITLE
nacos-operator方式部署集群报错：sh: 1: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by 77321660** [nacos-group/nacos-k8s#351]
部署文件
```yml
apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  name: nacos
spec:
  type: cluster
  image: nacos/nacos-server:v2.1.2-slim
  replicas: 3
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      cpu: 2
      memory: 2Gi
```
部署命令：
```sh
kubectl apply -f nacos_cluster.yaml
```

错误信息：
```
sh: 1: Syntax error: "(" unexpected
```
