### ISSUE TITLE
使用operator部署，无lease权限

### ISSUE THREAD

**Issue by KaKeimei** [nacos-group/nacos-k8s#367]
cannot get resource "leases" in API group "coordination.k8s.io"

需要在clusterrole中增加如下配置：

```
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - list
      - update
```
