### ISSUE TITLE
nacos-operator 部署 nacos 2.2.2 出错

### ISSUE THREAD

**Issue by bydongxing** [nacos-group/nacos-k8s#410]
使用 nacos-operator 按照 nacos_cluster_mysql.yaml 文件部署 nacos 2.2.2 的 nacos 集群，部署3 个实例，启动报错！错误信息:

```
com.alibaba.nacos.api.exception.runtime.NacosRuntimeException: errCode: 102, errMsg: dataSource or tableName is null 
```

``nacos_cluster_mysql.yaml`` 文件内容信息如下:
```
apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  name: nacos
  namespace: nacos-cluster-v222
spec:
  type: cluster
  image: nacos/nacos-server:v2.2.2
  replicas: 3
  resources:
    resources:
      limits:
        cpu: 1
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 4Gi
    # 启动数据卷，不然重启后数据丢失
  volume:
    enabled: true
    requests:
      storage: 10Gi
    storageClass: nfs-client
  mysqlInitImage: "registry.cn-hangzhou.aliyuncs.com/choerodon-tools/mysql-client:10.2.15-r0"
  database:
    type: mysql
    mysqlHost: mysql-master.mysql-cluster
    mysqlDb: "yidam_nacos_v222"
    mysqlUser: root
    mysqlPort: "3306"
    mysqlPassword: "yidam@220701"
  config: |
    management.endpoints.web.exposure.include=*
    spring.datasource.platform=mysql
    spring.sql.init.platform=mysql
    nacos.core.auth.enabled=true
    nacos.core.auth.plugin.nacos.token.secret.key=YUM3cE5aODBzaEJtaW1hNXMxdjdKYlZ3eFh2eVVvN2g=
    nacos.core.auth.server.identity.key=EvClymKR1LQ0r1Yb9Cp40VGJTQmuFXze
    nacos.core.auth.server.identity.value=Y8baoaJOcOvaf8iBkOZaATyaL141FxXL
```
