### ISSUE TITLE
How to set environment variables in Nacos Operator?

### ISSUE THREAD

**Issue by panzhc** [nacos-group/nacos-k8s#443]
I tried the following configuration according to the documentation:
[Custom configuration](https://github.com/nacos-group/nacos-k8s/tree/master/operator#custom-configuration)
```yaml
apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  name: nacos
spec:
  type: standalone
  env:
  - key: JVM_XMS
    value: 2g
```
 
When creating a Nacos object, the following error message is reported:
```
Nacos in version "v1alpha1" cannot be handled as a Nacos: strict decoding error: unknown field "spec.env[0].key"
```

How to configure environment variables in Nacos Operator?
Or how can I change the JVM configuration?

Operator Image: nacos/nacos-operator:latest.
Kubernetes Version: v1.26.6.

**Comment by panzhc** [comment]
Wrong document, should change the `key` to `name`:
```yaml
apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  name: nacos
spec:
  type: standalone
  env:
  - name: JVM_XMS
    value: 2g
```

**Comment by panzhc** [comment]
Wrong document, should change the `key` to `name`:
```yaml
apiVersion: nacos.io/v1alpha1
kind: Nacos
metadata:
  name: nacos
spec:
  type: standalone
  env:
  - name: JVM_XMS
    value: 2g
```
