### ISSUE TITLE
Nacos集群：curl: (6) Could not resolve host: GET; Unknown error

### ISSUE THREAD

**Issue by DanceKiddle** [nacos-group/nacos-k8s#53]
在k8s上使用nacaos集群服务注册功能：

springboot服务配置如下：
```
spring:
  application:
    name: nacos-client
  cloud:
    nacos:
      discovery:
        server-addr: nacos-0.nacos-headless.default.svc.cluster.local:8848
```

服务启动后，并没有注册成功，异常如下：

```
2019-07-18 15:27:21.562 ERROR 1 --- [TaskScheduler-1] o.s.c.a.nacos.discovery.NacosWatch       : Error watching Nacos Service change
 java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([nacos-0.nacos-headless.default.svc.cluster.local:8848]) tried: failed to req API:http://nacos-0.nacos-headless.default.svc.cluster.local:8848/nacos/v1/ns/service/list. code:503 msg: server is STARTING now, please try again later!
```

觉得是nacos集群没有配置正确
于是在nacos集群某个节点容器中运行curl结果如下：

```
sh-4.2# curl GET "http://localhost:8848/nacos/v1/ns/raft/state"
curl: (6) Could not resolve host: GET; Unknown error

```
查看/etc/hosts：
```
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
172.20.2.72	nacos-1.nacos-headless.default.svc.cluster.local.	nacos-1
```
没有发现异常。。
其他pod都是如此。
镜像用的目前的latest版本，部署方式是教程中的nfs可伸缩版。

不知道问题出在哪里，请教各位大神。
