### ISSUE TITLE
NACOS的K8S部署文档：nacos-pvc-nfs.yaml有问题，集群的时候选举失败！

### ISSUE THREAD

**Issue by hyj1986** [nacos-group/nacos-k8s#63]
我在按照nacos-k8s/deploy/nacos/nacos-pvc-nfs.yaml文档去部署的时候，发现集群一直失败，报错：
#### server is STARTING now, please try again later!
经过 @paderlol 的指导，去掉nacos-pvc-nfs.yaml中关于readiness的配置，然后就可以成功了。
```
readinessProbe:
    httpGet:
        port: client-port
        path: /nacos/v1/console/health/readiness
    initialDelaySeconds: 60
    timeoutSeconds: 3
```

由于是官方的指导文件，建议是否更新一下，以确保案例可以执行成功？
