### ISSUE TITLE
基于去除了mysql主从配置的那个提交进行部署，在pod中nacos启动不成功。

### ISSUE THREAD

**Issue by Tidusww** [nacos-group/nacos-k8s#94]
/home/nacos/logs/config-fatal.log中的报错信息：
2020-02-21 15:36:56,330 ERROR [master-db] master db not found.
2020-02-21 15:37:00,350 ERROR [db-error] master db  down.
2020-02-21 15:37:00,743 WARN useAddressServer:true
2020-02-21 15:37:00,854 WARN isQuickStart:false
2020-02-21 15:37:00,910 ERROR Nacos Server did not start because dumpservice bean construction failure :
No DataSource set

在statufulset中有配置pod的环境变量：
        - name: MYSQL_SERVICE_HOST
          valueFrom:
            configMapKeyRef:
              key: mysql.db.host
              name: cdp-nacos-cm
        - name: MYSQL_SERVICE_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: mysql.db.name
              name: cdp-nacos-cm
        - name: MYSQL_SERVICE_PORT
          valueFrom:
            configMapKeyRef:
              key: mysql.port
              name: cdp-nacos-cm
        - name: MYSQL_SERVICE_USER
          valueFrom:
            configMapKeyRef:
              key: mysql.user
              name: cdp-nacos-cm
        - name: MYSQL_SERVICE_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: mysql.password
              name: cdp-nacos-cm

在pod中对数据库telnet也是成功的，请问这个问题是什么原因导致的？

**Comment by paderlol** [comment]
镜像使用得什么版本？

**Comment by paderlol** [comment]
你要看下pod里面的MYSQL_SERVICE_HOST环境变量输出的是什么，还有如果你是使用的不是latest镜像就不行，目前只有latest镜像移除了主从

**Comment by paderlol** [comment]
必须是这个镜像版本nacos/nacos-server:latest

**Comment by Tidusww** [comment]
确认了镜像拉的是nacos/nacos-server:latest
Normal  Pulled     21s   kubelet, aks-nodepool1-25892561-11  Successfully pulled image "nacos/nacos-server:latest"
----------------------------------------
另外pod中打印MYSQL_SERVICE_HOST：
[root@cdp-nacos-0 nacos]# echo $MYSQL_SERVICE_HOST
cdp-nacos-db-svc
----------------------------------------
telnet结果：
[root@cdp-nacos-0 nacos]# telnet cdp-nacos-db-svc 3306
Trying 10.48.57.249...
Connected to cdp-nacos-db-svc.
Escape character is '^]'.
J
8.0.18J.l
         \Q%#
             %ZjV.OM8mysql_native_password
----------------------------------------
这个库确认是正常在跑的，已经在上面执行了nacos的初始化脚本

**Comment by paderlol** [comment]
你插件驱动换了吗？默认不支持mysql8

**Comment by Tidusww** [comment]
确认了镜像拉的是nacos/nacos-server:latest
Normal  Pulled     21s   kubelet, aks-nodepool1-25892561-11  Successfully pulled image "nacos/nacos-server:latest"

另外pod中打印MYSQL_SERVICE_HOST：
[root@cdp-nacos-0 nacos]# echo $MYSQL_SERVICE_HOST
cdp-nacos-db-svc

telnet结果：
[root@cdp-nacos-0 nacos]# telnet cdp-nacos-db-svc 3306
Trying 10.48.57.249...
Connected to cdp-nacos-db-svc.
Escape character is '^]'.
J
8.0.18J.l
         \Q%#
             %ZjV.OM8mysql_native_password

这个库确认是正常在跑的，已经在上面执行了nacos的初始化脚本

ps：之前试过如果没有配置MYSQL_SERVICE_HOST的话，报错日志里面会提示无法处理mysql连接串中的${MYSQL_SERVICE_HOST}占位符的。

**Comment by Tidusww** [comment]
> 你插件驱动换了吗？默认不支持mysql8

所以是mysql8的问题？这个我等下换成5.7.x的试试

**Comment by paderlol** [comment]
是的，你想用mysql8，就自己想办法挂卷进去，docker有例子，但是k8s不好挂

**Comment by Tidusww** [comment]
[root@cdp-nacos-0 logs]# telnet cdp-nacos-db-svc 3306
Trying 10.48.79.239...
Connected to cdp-nacos-db-svc.
Escape character is '^]'.
Q
5.7.25-28-log�#w
                _lx"k�-JI!2|c]8=F.mysql_native_password

换成了mysql5.7也是同样的报错...

其实那个mysql8是外部数据库来的，用EP访问，所以不会有k8s挂载问题...

至于这个报错还有其他头绪吗，或者我先用回myslq主从配置的那个版本试试？镜像要用哪个版本？

**Comment by paderlol** [comment]
我说的挂载是数据库驱动不支持

**Comment by paderlol** [comment]
Latest版本我昨天测试过的，5.7没有任何问题

**Comment by paderlol** [comment]
你可以通过这些方式排查下
1.初始化脚本是否成功初始化了，重点是不是初始化到正确的库了。
2.连接数据库dbname配置是否配置正确
3.然后k8s使用的哪个例子为原型进行部署的？

**Comment by paderlol** [comment]
建议你不要退回主从版本，目前指定版本号的都是主从版本，只有latest去掉了，还有你可以尝试用nacos/nacos-mysql:5.7 来作为数据库镜像尝试

**Comment by paderlol** [comment]
我刚想起来还有一个,你传递的是你的serviceName可能程序内部并不能解析这个,你试着把你的MySQL service name 在k8s里面从cdp-nacos-db-svc改成mysql,然后去除对MYSQL_SERVICE_HOST的赋值,k8s默认会根据服务名解析到对应的ip

``` yaml
apiVersion: v1
kind: Service
metadata:
  name: mysql ##配置这个可以在nacos里面无需配置MYSQL_SERVICE_HOST
  labels:
    name: mysql
spec:
  ## 其他的配置 不管你是LoadBalancer/ExternalName
```

**Comment by Tidusww** [comment]
@paderlol 非常感谢，mysql的问题解决了，确实是mysql8的问题，7是可以连接的。

不过现在有个新问题，nacos启动的时候报错找不到/home/nacos/conf/cluster.conf，在pod中/home/nacos/conf下确实没有这个文件，这个文件是peer-finder生成的？怎么知道peer-finder有没有正常工作？
（nacos的k8s配置文件我是参考项目中的deploy/nacos/nacos-pvc-nfs.yaml修改的）

**Comment by paderlol** [comment]
1. 确保peer finder插件的卷挂到和nacos同一个目录
2. 确认ClusterIp为None
3. 去pod里面 执行ps -ef | grep peer-finder 看进程是否存在
4. 可以进去pod,在plugins目录下找到plugin.sh,手动执行下,看看报错原因是什么

**Comment by paderlol** [comment]
``` yaml
  - name: SERVICE_NAME
# 这里需要改成你自己的svc的名称
              value: "cdp-nacos-svc"
            - name: DOMAIN_NAME
              value: "cluster.local"
            - name: POD_NAMESPACE

```

**Comment by Tidusww** [comment]
1. peer finder插件的卷和nacos挂载的卷是同一个，而且目录一样
```
    initContainers:
        - name: peer-finder-plugin-install
          image: nacos/nacos-peer-finder-plugin:1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: cdp-nacos-plugindir-pvc
              mountPath: /home/nacos/plugins/peer-finder
...
    containers
        volumeMounts:
            - name: cdp-nacos-plugindir-pvc
              mountPath: /home/nacos/plugins/peer-finder
```

2. ClusterIp确定是None的

3. pod刚启动起来后，peer-finder进程是不存在的

4. 进去plugins/peer-finder/，手动执行
```
./peer-finder -on-start=/home/nacos/plugins/peer-finder/on-start.sh -on-change=/home/nacos/plugins/peer-finder/on-change.sh -service=cdp-nacos-svc -domain=cluster.local
```
输出结果：
```
2020/02/24 13:36:48 execing: /home/nacos/plugins/peer-finder/on-start.sh with stdin: cdp-nacos-0.cdp-nacos-svc.dev.svc.cluster.local
2020/02/24 13:36:48
2020/02/24 13:36:49 Have not found myself in list yet.
My Hostname: cdp-nacos-0.cdp-nacos-svc.dev.svc.cluster.local
Hosts in list: cdp-nacos-0.cdp-nacos-svc.dev.svc.cluster.local
2020/02/24 13:36:50 Have not found myself in list yet.
My Hostname: cdp-nacos-0.cdp-nacos-svc.dev.svc.cluster.local
Hosts in list: cdp-nacos-0.cdp-nacos-svc.dev.svc.cluster.local
...
```
这时候再出去看nacos的启动日志就显示启动成功了
